In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Python基础补充内容
#### 1、列表推导式与条件赋值

In [5]:
L =[]

def my_func(x):
    return 2*x

for i in range(10):
    L.append(my_func(i))
    
L

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [7]:
[my_func(i) for i in range(10)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [93]:
all_data = [['John', 'Emily', 'Michael', 'Mary', 'Steven'],
            ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]
result = [name for names in all_data for name in names if name.count('e') >=2]

result

['Steven']

In [95]:
some_tuples = [(1,2,3),(4,5,6),(7,8,9)]
flattened = [x for tup in some_tuples for x in tup]
flattened

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [101]:
tem = [[x for x in tup]for tup in some_tuples]
tem

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
value = 'cat' if 2>1 else 'dog'

value

'cat'

In [14]:
def apply_to_list(some_list, f):
    return [f(x) for x in some_list]

ints = [4, 0, 1, 5, 6]
apply_to_list(ints, lambda x: x*2)

[8, 0, 2, 10, 12]

In [15]:
[(lambda x: 2*x)(i) for i in range(5)]

[0, 2, 4, 6, 8]

In [16]:
list(map(lambda x: 2*x, range(5)))
[0, 2, 4, 6, 8]

[0, 2, 4, 6, 8]

In [18]:
seq1 = ['foo', 'bar', 'baz']

seq2 = ['one', 'two', 'three']

zipped = zip(seq1,seq2)

list(zipped)

[('foo', 'one'), ('bar', 'two'), ('baz', 'three')]

In [20]:
for i, (a, b) in enumerate(zip(seq1, seq2)):
     print('{0}: {1}, {2}'.format(i, a, b))

0: foo, one
1: bar, two
2: baz, three


In [40]:
pitchers = [('Nolan', 'Ryan'), ('Roger', 'Clemens'),
             ('Schilling', 'Curt')]
print(pitchers)
first_names, last_names = zip(*pitchers)
unzipped = zip(*pitchers)
print(list(unzipped))
print(first_names)

#('Nolan', 'Roger', 'Schilling')
print(last_names)

# ('Ryan', 'Clemens', 'Curt')

[('Nolan', 'Ryan'), ('Roger', 'Clemens'), ('Schilling', 'Curt')]
[('Nolan', 'Roger', 'Schilling'), ('Ryan', 'Clemens', 'Curt')]
('Nolan', 'Roger', 'Schilling')
('Ryan', 'Clemens', 'Curt')


## 二、NumPy基础

In [47]:
np.linspace(1,5,11) #起始、终止（包含）、样本个数

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [44]:
np.arange(1,5,0.4) #起始、终止（不包含）、步长

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6])

In [48]:
np.logspace(0.1,1,10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [49]:
my_list = ['a', 'b', 'c', 'd']

np.random.choice(my_list, 2, replace=True, p=[0.1, 0.7, 0.1, 0.1])

array(['b', 'b'], dtype='<U1')

In [50]:
np.random.choice(my_list,(3,3))

array([['a', 'b', 'b'],
       ['d', 'c', 'd'],
       ['b', 'b', 'c']], dtype='<U1')

In [53]:
a = np.array([-2, -5, 0, 1, 3, -1])

In [59]:
np.nonzero(a)  # 返回的是非零数的索引
#  a = np.array([-2,-5,0,1,3,-1])

a.argmax()
# 4

a.argmin()
# 1


1

In [60]:
a = np.array([1,2,3])
b = np.array([2,3,4])

np.dot(a,b)

20

In [62]:
martix_target = np.arange(4).reshape(-1,2)
martix_target

array([[0, 1],
       [2, 3]])

In [63]:
np.linalg.norm(martix_target, 'fro')

3.7416573867739413

In [64]:
np.linalg.norm(martix_target, np.inf)

5.0

In [65]:
np.linalg.norm(martix_target, 2)

3.702459173643833

In [66]:
vector_target =  np.arange(4)
vector_target

array([0, 1, 2, 3])

In [67]:
np.linalg.norm(vector_target, np.inf)

3.0

In [69]:
np.linalg.norm(vector_target, 2)

3.7416573867739413

In [70]:
np.linalg.norm(vector_target, 3)

3.3019272488946263

In [76]:
a = np.arange(4).reshape(-1,2)
# array([[0, 1],
#        [2, 3]])
    
b = np.arange(-2,2).reshape(2,2)
# array([[-2, -1],
#        [ 0,  1]])

array([[-2, -1],
       [ 0,  1]])

In [72]:
a@b

array([[ 0,  1],
       [-4,  1]])

### 练习
EX1:利用列表推导式写矩阵乘法

In [87]:
M1 = np.random.rand(2,3)

M2 = np.random.rand(3,4)

res = [[sum([M1[i][k] * M2[k][j] for k in range(M1.shape[1])]) for j in range(M2.shape[1])] for i in range(M1.shape[0])]
print(res)
# res = [[sum([M1[i][k] * M2[k][j] for k in range(M1.shape[1])]) for j in range(M2.shape[1])] for i in range(M1.shape[0])]
((M1@M2 - res) < 1e-15).all()

[[1.1737002781563035, 0.658500937211033, 0.6516814336294817, 1.16595858874867], [0.704473194208938, 0.32256919014693664, 0.19519908882478537, 0.5804910729720212]]


True

In [102]:
M1 = np.random.rand(2,3)

M2 = np.random.rand(3,4)
res2 = np.empty((M1.shape[0],M2.shape[1]))
res2 = M1[i][k] * M2[k][j] for i in range(M1.shape[0]) for j in range(M2.shape[1]) for k in range(M1.shape[1])
print(res2)

SyntaxError: invalid syntax (<ipython-input-102-397824187e1b>, line 5)

EX2: 更新矩阵

In [110]:
A = np.arange(1,10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
1/A

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

In [116]:
B=A*np.sum(1/A,axis=1).reshape(3,1)

In [117]:
B

array([[1.83333333, 3.66666667, 5.5       ],
       [2.46666667, 3.08333333, 3.7       ],
       [2.65277778, 3.03174603, 3.41071429]])

In [122]:
np.random.seed(0)
A = np.random.randint(10, 20, (8, 5))
A

array([[15, 10, 13, 13, 17],
       [19, 13, 15, 12, 14],
       [17, 16, 18, 18, 11],
       [16, 17, 17, 18, 11],
       [15, 19, 18, 19, 14],
       [13, 10, 13, 15, 10],
       [12, 13, 18, 11, 13],
       [13, 13, 17, 10, 11]])

In [121]:
np.sum(A,axis=0)

array([120, 111, 129, 116, 101])

In [123]:
A.sum(1)

array([68, 73, 80, 79, 85, 61, 67, 64])

In [129]:
B = A.sum(0)*A.sum(1).reshape(-1,1)/A.sum()
B

array([[14.14211438, 13.08145581, 15.20277296, 13.67071057, 11.90294627],
       [15.18197574, 14.04332756, 16.32062392, 14.67590988, 12.77816291],
       [16.63778163, 15.38994801, 17.88561525, 16.08318891, 14.0034662 ],
       [16.42980936, 15.19757366, 17.66204506, 15.88214905, 13.82842288],
       [17.67764298, 16.35181976, 19.0034662 , 17.08838821, 14.87868284],
       [12.68630849, 11.73483536, 13.63778163, 12.26343154, 10.67764298],
       [13.93414211, 12.88908146, 14.97920277, 13.46967071, 11.72790295],
       [13.3102253 , 12.31195841, 14.3084922 , 12.86655113, 11.20277296]])

In [140]:
np.random.seed(0)
m, n, p = 100, 80, 50
B = np.random.randint(0, 2, (m, p))
U = np.random.randint(0, 2, (p, n))
Z = np.random.randint(0, 2, (m, n))
def solution(B=B, U=U, Z=Z):
    L_res = []
    for i in range(m):
        for j in range(n):
            norm_value = ((B[i]-U[:,j])**2).sum()
            L_res.append(norm_value*Z[i][j])
    return sum(L_res)
solution(B, U, Z)

100566

In [ ]:
from timeit import timeit
t0 = timeit('solution()', 'from __main__ import solution', number=100)